/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityStory = IDL.Record({
  'name' : IDL.Text,
  'story' : IDL.Text,
  'timestamp' : IDL.Int,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const ConsultationSubmission = IDL.Record({
  'interest' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCommunityStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addConsultationSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCommunityStories' : IDL.Func([], [IDL.Vec(CommunityStory)], ['query']),
  'getAllConsultationSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ConsultationSubmission)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityStory = IDL.Record({
    'name' : IDL.Text,
    'story' : IDL.Text,
    'timestamp' : IDL.Int,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const ConsultationSubmission = IDL.Record({
    'interest' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCommunityStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addConsultationSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCommunityStories' : IDL.Func(
        [],
        [IDL.Vec(CommunityStory)],
        ['query'],
      ),
    'getAllConsultationSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ConsultationSubmission)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };